# Copyright 2022, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: job-build

on:
  workflow_call:

jobs:
  license:
    name: 'License Check'
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/license-check@master

  links:
    name: Links
    runs-on: ubuntu-latest
    steps:
      - uses: seL4/ci-actions/link-check@master

  gitlint:
    name: Gitlint
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/gitlint@master

  whitespace:
    name: 'Trailing Whitespace'
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/git-diff-check@master

  shell:
    name: 'Portable Shell'
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/bashisms@master

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/style@master
