# Copyright 2022, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: job-build

on:
  workflow_call:
    inputs:
      run_hw_test:
        description: 'Run hardware test'
        default: 'false'

jobs:
  code:
    name: Freeze Code
    runs-on: ubuntu-latest
    outputs:
      xml: ${{ steps.repo.outputs.xml }}
    steps:
    - id: repo
      uses: seL4/ci-actions/repo-checkout@master
      with:
        manifest_repo: sel4webserver-manifest
        manifest: master.xml

  build:
    name: Build
    needs: code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ODROID_XU4, ODROID_C2, TX2]
    steps:
    - uses: seL4/ci-actions/webserver@master
      with:
        xml: ${{ needs.code.outputs.xml }}
        platform: ${{ matrix.platform }}
    - name: Upload images
      uses: actions/upload-artifact@v4
      with:
        name: images-${{ matrix.platform }}
        path: '*-images.tar.gz'

  hw-run:
    name: Hardware
    if: if: ${{ (github.repository_owner == 'seL4') &&
                (inputs.run_hw_test == 'true') }}
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        platform: [ODROID_XU4, ODROID_C2, TX2]
    # do not run concurrently with other workflows, but do run concurrently in the build matrix
    concurrency: webserver-hw-${{ strategy.job-index }}
    steps:
      - name: Get machine queue
        uses: actions/checkout@v4
        with:
          repository: seL4/machine_queue
          path: machine_queue
          token: ${{ secrets.PRIV_REPO_TOKEN }}
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: images-${{ matrix.platform }}
      - name: Run
        uses: seL4/ci-actions/webserver-hw@master
        with:
          platform: ${{ matrix.platform }}
          index: $${{ strategy.job-index }}
        env:
          HW_SSH: ${{ secrets.HW_SSH }}
