# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: PR

on: [pull_request]

jobs:
  checks:
    uses: ./.github/workflows/workflow-checks.yml

  ci:
    uses: ./.github/workflows/workflow-build.yml
    secrets: inherit

  test:
    needs: [ci]
    uses: ./.github/workflows/workflow-test.yml
    secrets: inherit
