# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: PR

on: [pull_request]

jobs:
  checks:
    uses: ./.github/workflows/job-checks.yml

  ci:
    uses: ./.github/workflows/job-build.yml
    secrets: inherit
