# Copyright 2022, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# seL4 web server demo app regression tests + manifest deployment

name: Web Server Demo

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'

  # allow manual trigger
  workflow_dispatch:

  # allow explict trigger from other repos when dependencies have changed
  repository_dispatch:
    types: [deps-update]

jobs:
  checks:
    uses: ./.github/workflows/workflow-checks.yml

  ci:
    uses: ./.github/workflows/workflow-build.yml
    secrets: inherit # pass all secrets
    with:
      run_hw_test: true

  deploy:
    name: Deploy manifest
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
    - name: Deploy
      uses: seL4/ci-actions/manifest-deploy@master
      with:
        xml: ${{ needs.ci.code.outputs.xml }}
        manifest_repo: sel4webserver-manifest
      env:
        GH_SSH: ${{ secrets.CI_SSH }}
